
https://localhost:32773/pokemon/solgaleo
Accept: application/json

###

https://localhost:32773/pokemon/translated/lucario
Accept: application/json

###

https://localhost:32773/pokemon/abcd
Accept: application/json

###

https://localhost:32773/pokemon/translated/abcd
Accept: application/json

###